### ISSUE TITLE
Broken since vsc 1.5

### ISSUE THREAD

**Issue by JCarran0** [naumovs/vscode-ext-node-module-resolve#2]
This seems to have broken after upgrading to vsc 1.5.

**Comment by yurickgomes** [comment]
It's only working with "import from" syntax

**Comment by lxa108** [comment]
+1
Still works for project modules. However doesn't resolve other installed in 'node_modules' folder.

**Comment by iamsergii** [comment]
Update and it should work fine

**Comment by yurickgomes** [comment]
Thanks sergirocks,
This extension should be included by default on VS Code,
Congratutalions.

**Comment by JCarran0** [comment]
Confirmed. Works after update 👍 

Thanks for the great extension!
