### ISSUE TITLE
Doesn't work when try to import .less file

### ISSUE THREAD

**Issue by plowsirius** [naumovs/vscode-ext-node-module-resolve#5]
Hi,
This extension is very help until I found this little inconvenience.
I have a directory structure like this.

app/
&ensp;&ensp;src/
&ensp;&ensp;&ensp;A.jsx
&ensp;&ensp;&ensp;B.less

in A.jsx:
```import './B.less';```

when I wanted to import style from file B.less into A.jsx, but it does not work.And I notice this is related to function filterEs6 in src/lib/definition-provider.js. Maybe in there can be a bypass for *.less, *.css. Looking forward to your reply.

**Comment by iamsergii** [comment]
Hey. By default this extension resolves only js files. You can configure file extensions to resolve in editor settings > javascript.commonjs.resolve.extensions 

EDIT: also you have to add less to the "javascript.commonjs.resolve.languages" so the extension would be enabled in less files
