### ISSUE TITLE
Open file in new tab?

### ISSUE THREAD

**Issue by tnrich** [naumovs/vscode-ext-node-module-resolve#7]
Hey there,

This extension appears to always open the new file in the same tab, instead of opening the file in a new tab. Maybe if the user held shift it would open the file in a new tab? 

Thanks!

**Comment by iamsergii** [comment]
I quickly checked and found no solution for this.

This is not a part of the extension, but the vscode itself. Create an issue in the [VSCode](https://github.com/Microsoft/vscode/issues) repo
